### ISSUE TITLE
Is get_ranked_posts request returns pinned always?

### ISSUE THREAD

**Issue by dkildar** [ecency/vision-next#90]
https://developers.hive.io/apidefinitions/#bridge.get_ranked_posts

Question: is this request always returns pinned posts even if there were pinned earlier than all posts in a first page of this request?

**Comment by feruzm** [comment]
> https://developers.hive.io/apidefinitions/#bridge.get_ranked_posts
> 
> Question: is this request always returns pinned posts even if there were pinned earlier than all posts in a first page of this request?

@dkildar Yes, when sorting is `hot` or `trending`, it should fetch all pinned posts in first query. It doesn't show them when sort is `created`.
